### ISSUE TITLE
Is it posible using esp01 board?

### ISSUE THREAD

**Issue by Krazydrumz** [AronHetLam/ATEM_tally_light_with_ESP8266#48]
Thank's sir...great job,,your project it's worl for me,it's help alot..I'm curious is it posible using esp01,reason for lowering cost

**Comment by AronHetLam** [comment]
It should be, and It's been asked once before, but I don't think anyone's used/tried it yet. Take a look there https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/issues/16#issuecomment-758737447.

I don't know how technical you are, but as the esp-01 has a lot fewer pins, you'd need to modify the code to be compatible. I get it to compile by:
1. Selecting `Generic ESP8266 Module (esp8266)`
2. Removing the `D` in `D1`, `D2`... etc. here https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/blob/a83de93c20710f8e50fd8b8bf51cdf5c089a328f/ATEM_tally_light/ATEM_tally_light.ino#L51-L59

2. Replace `D7` with `13` here https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/blob/a83de93c20710f8e50fd8b8bf51cdf5c089a328f/ATEM_tally_light/ATEM_tally_light.ino#L102

Besides that you also need a USB-programmer to program the esp-01 with, as it doesn't have a USB plug or chip.
And in order to properly use gpio1 and gpio3 you probably need to disable the Serial communication for it not to interfere.
