### ISSUE TITLE
Resistors

### ISSUE THREAD

**Issue by SamVimes78** [AronHetLam/ATEM_tally_light_with_ESP8266#89]
I just did some research about the resistors you are using and wanted to know if there's a better choice:

The resistors included in the set from your link are suited for a 12V power supply. My guess is that the voltage for the LEDs is up to 3,2V. Most rgb LEDs i found on aliexpress need 2V for red and 3,2V for blue/green. My guess (i'm no expert) is that this is true for most common cathode rgb LEDs and probably also for the ones you got.

ESP8266 and ESP32 both are 3,3V boards and that's also the voltage provided by the GPIO pins.

If you want these LEDs (especially the red part) to be as bright as possible, you'll need to use resistors with as low as possible values. My calculation is that the optimal resistors are 68Ω for red and 5.1Ω for the other two anodes.
In other words:
For the LEDs to be as bright as possible skip the resistors for blue and green (they'll probably be fine without) and use 68Ω for the red anode.

The 120Ω resistors in your example definitely work. You lose some brightness but probably not too much because modern LEDs should be rather efficient. I just stumbled over the LED specs (at aliexpress), saw the different voltages for red and blue/green and wondered why you are using the same resistors for all colors.

And after all this googling, calculating and headscratching i felt the urge to share my findings.

Thanks for your work!

Btw:
It seems to be rather common for this kind of projects to just use 3 identical resistors. I found only one source that took the voltage difference into account. Maybe I'm too much of a stickler.

**Comment by AronHetLam** [comment]
Yes, you are absolutely right, the 120 ohm resistors are too much, but I'm pretty sure they're good for 5v curcuits (which is what I had parts for before getting the ESPs 😊). For 12v curcuits I believe you need 470 ohm resistors. 

But as people might get differently specced LEDs, they would also need to get differently specced resistors. Since it works fine and won't burn out the LEDs with the 120 ohm resistors, I just left it at that for simplicity. Simplicity is also why I don't mention using different resistors for the three colors.

I won't update it in the wiki, but you can definitely change them out.
However, I would recommend to over-spec the resistors a little bit, just to not push the LEDs to their limits and have them last longer. If you really need brighter, I would get some neopixels.
